package EchoApp;


/**
* EchoApp/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EchoApp.idl
* Wednesday, March 8, 2023 8:48:41 AM ICT
*/

public interface EchoOperations 
{
  String EchoString ();
} // interface EchoOperations
